let d = new Date()
console.log(d)
console.log(typeof d)

let dateobj = new Date()
console.log(dateobj)
console.log(typeof dateobj)
console.log(dateobj.getDate())
console.log(dateobj.getMonth())
console.log(dateobj.getFullYear())
console.log(dateobj.getDay())
console.log(dateobj.getHours())
console.log(dateobj.getMinutes())
console.log(dateobj.getSeconds())
console.log(dateobj.getMilliseconds())
console.log(dateobj.getTime())
